Repository SWPC-Team-You-Can-Do-It/ppurisam, pull requests merged in 2024-11, with the labels that each got.

#18 refactor: docker-compose.yml 파일 볼륨 수정
  docker-compose.yml
Labels: refactor

#20 feat: nginx 연동
  docker-compose.yml
  nginx/nginx.conf
Labels: feature

#26 bug: nginx /@vite/ 경로 웹소켓 프록시 설정
  nginx/nginx.conf
Labels: bug

#30 setting: prometheus 통신을 위한 nginx-exporter 설정
  docker-compose.yml
  nginx/nginx.conf
Labels: setting

#32 setting: 이미지 경로 추가
  nginx/nginx.conf
Labels: setting

#34 refactor: readme 기본틀
  README.md
Labels: refactor
